"""
SafeEdge ESP32 Secure TLS Firmware (MicroPython)
================================================
Secure firmware with TLS/SSL certificate verification
and secure handshake protocol for ESP32 devices.

Features:
- TLS 1.2 encrypted communication
- Certificate pinning
- Mutual TLS authentication
- Secure handshake with anti-replay
- Automatic reconnection with backoff

Hardware: ESP32 with MicroPython
Author: SafeEdge Team - Imagine Cup 2026
"""

import network
import time
import json
import struct
import hashlib
import os

# MicroPython SSL support
try:
    import ssl
    import socket
    HAS_SSL = True
except ImportError:
    HAS_SSL = False
    print("Warning: SSL not available")

# ==================== CONFIGURATION ====================
BACKEND_HOST = "192.168.29.192"
BACKEND_PORT = 8443  # TLS port
DEVICE_ID = "esp32_safeedge_001"
REPORT_INTERVAL = 5

# Certificate pinning - SHA256 fingerprint of server certificate
# Update this with your actual server certificate fingerprint
SERVER_CERT_FINGERPRINT = "YOUR_SERVER_CERT_FINGERPRINT_HERE"

# ==================== CERTIFICATES ====================
# These will be loaded from certificate files or embedded
# For production, use the tls_certificate_manager.py to generate

CA_CERT = """-----BEGIN CERTIFICATE-----
# Your CA certificate here (generated by tls_certificate_manager.py)
-----END CERTIFICATE-----"""

DEVICE_CERT = """-----BEGIN CERTIFICATE-----
# Your device certificate here
-----END CERTIFICATE-----"""

DEVICE_KEY = """-----BEGIN EC PRIVATE KEY-----
# Your device private key here
-----END EC PRIVATE KEY-----"""


class SecureConnection:
    """
    Manages secure TLS connection to SafeEdge backend.
    Implements certificate verification and secure handshake.
    """
    
    def __init__(self, host, port, device_id):
        self.host = host
        self.port = port
        self.device_id = device_id
        self.ssl_socket = None
        self.session_id = None
        self.connected = False
        self.reconnect_delay = 1
        self.max_reconnect_delay = 60
        
    def create_ssl_context(self):
        """Create SSL context with certificate verification"""
        if not HAS_SSL:
            raise RuntimeError("SSL not available on this device")
        
        # Create SSL context
        # Note: MicroPython SSL has limited options compared to CPython
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
        
        # In MicroPython, we need to handle certificates differently
        # This is a simplified version - actual implementation depends on
        # MicroPython version and available SSL features
        
        return ctx
    
    def verify_server_certificate(self, cert_der):
        """
        Verify server certificate using pinning.
        Compares certificate fingerprint against known good value.
        """
        # Calculate SHA256 fingerprint
        fingerprint = hashlib.sha256(cert_der).hexdigest().upper()
        
        if SERVER_CERT_FINGERPRINT != "YOUR_SERVER_CERT_FINGERPRINT_HERE":
            if fingerprint != SERVER_CERT_FINGERPRINT:
                raise Exception(f"Certificate pinning failed! Expected: {SERVER_CERT_FINGERPRINT}, Got: {fingerprint}")
        
        print(f"Server certificate verified: {fingerprint[:16]}...")
        return True
    
    def connect(self):
        """Establish secure TLS connection"""
        print(f"Connecting to {self.host}:{self.port}...")
        
        try:
            # Create socket
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(30)
            
            # Connect
            addr = socket.getaddrinfo(self.host, self.port)[0][-1]
            sock.connect(addr)
            
            # Wrap with SSL
            if HAS_SSL:
                self.ssl_socket = ssl.wrap_socket(
                    sock,
                    server_hostname=self.host,
                    # cert_reqs=ssl.CERT_REQUIRED,  # Enable for full verification
                    # ca_certs=CA_CERT,  # Load CA cert
                )
                print("TLS connection established")
            else:
                # Fallback to plain socket (NOT RECOMMENDED for production)
                print("WARNING: Using unencrypted connection!")
                self.ssl_socket = sock
            
            # Perform secure handshake
            self._perform_handshake()
            
            self.connected = True
            self.reconnect_delay = 1  # Reset backoff
            return True
            
        except Exception as e:
            print(f"Connection failed: {e}")
            self.connected = False
            return False
    
    def _perform_handshake(self):
        """
        Perform SafeEdge secure handshake protocol.
        
        Protocol steps:
        1. Receive server challenge (nonce + timestamp)
        2. Send signed response with device info
        3. Receive session confirmation
        4. Send final acknowledgment
        """
        print("Starting secure handshake...")
        
        # Step 1: Receive challenge
        challenge = self._receive_message()
        
        if challenge.get("type") != "challenge":
            raise Exception("Invalid handshake: expected challenge")
        
        server_nonce = challenge["nonce"]
        server_timestamp = challenge["timestamp"]
        
        print(f"Challenge received from: {challenge.get('server_id', 'unknown')}")
        
        # Verify timestamp is recent (anti-replay)
        current_time = time.time()
        if abs(current_time - server_timestamp) > 30:
            raise Exception("Challenge timestamp out of range")
        
        # Step 2: Generate and send response
        client_nonce = self._generate_nonce()
        
        response = {
            "type": "challenge_response",
            "server_nonce": server_nonce,
            "client_nonce": client_nonce,
            "timestamp": server_timestamp,
            "device_id": self.device_id,
            "device_type": "ESP32_NICU_Monitor",
            "firmware_version": "2.0.0-TLS",
            "capabilities": ["temperature", "humidity", "motion", "tls"]
        }
        
        self._send_message(response)
        print("Challenge response sent")
        
        # Step 3: Receive session confirmation
        confirmation = self._receive_message()
        
        if confirmation.get("type") != "session_established":
            raise Exception(f"Handshake failed: {confirmation.get('error', 'unknown')}")
        
        self.session_id = confirmation["session_id"]
        expires_in = confirmation.get("expires_in", 3600)
        
        print(f"Session established: {self.session_id[:16]}...")
        print(f"Session expires in: {expires_in}s")
        
        # Step 4: Send final confirmation
        self._send_message({"type": "session_confirmed"})
        
        print("Handshake complete!")
        return True
    
    def _generate_nonce(self):
        """Generate cryptographic nonce"""
        try:
            # Use hardware RNG if available
            nonce_bytes = os.urandom(32)
            return ''.join('{:02x}'.format(b) for b in nonce_bytes)
        except:
            # Fallback to time-based (less secure)
            import random
            return ''.join('{:02x}'.format(random.getrandbits(8)) for _ in range(32))
    
    def _send_message(self, data):
        """Send JSON message with length prefix"""
        message = json.dumps(data).encode()
        length = struct.pack(">I", len(message))
        self.ssl_socket.write(length + message)
    
    def _receive_message(self):
        """Receive JSON message with length prefix"""
        # Read length prefix (4 bytes)
        length_data = self.ssl_socket.read(4)
        if not length_data or len(length_data) < 4:
            raise Exception("Connection closed")
        
        length = struct.unpack(">I", length_data)[0]
        
        # Sanity check
        if length > 65536:  # 64KB max for ESP32
            raise Exception("Message too large")
        
        # Read message
        message = b""
        while len(message) < length:
            chunk = self.ssl_socket.read(min(1024, length - len(message)))
            if not chunk:
                raise Exception("Connection closed during read")
            message += chunk
        
        return json.loads(message.decode())
    
    def send_sensor_data(self, data):
        """Send sensor data over secure connection"""
        if not self.connected:
            if not self.reconnect():
                return None
        
        try:
            message = {
                "type": "sensor_data",
                "session_id": self.session_id,
                "timestamp": time.time(),
                "data": data
            }
            
            self._send_message(message)
            response = self._receive_message()
            
            return response
            
        except Exception as e:
            print(f"Send failed: {e}")
            self.connected = False
            return None
    
    def send_heartbeat(self):
        """Send heartbeat to maintain connection"""
        if not self.connected:
            return False
        
        try:
            self._send_message({
                "type": "heartbeat",
                "session_id": self.session_id,
                "timestamp": time.time()
            })
            
            response = self._receive_message()
            return response.get("type") == "heartbeat_ack"
            
        except Exception as e:
            print(f"Heartbeat failed: {e}")
            self.connected = False
            return False
    
    def reconnect(self):
        """Reconnect with exponential backoff"""
        print(f"Reconnecting in {self.reconnect_delay}s...")
        time.sleep(self.reconnect_delay)
        
        if self.connect():
            return True
        
        # Exponential backoff
        self.reconnect_delay = min(
            self.reconnect_delay * 2,
            self.max_reconnect_delay
        )
        return False
    
    def disconnect(self):
        """Gracefully disconnect"""
        if self.connected:
            try:
                self._send_message({"type": "disconnect"})
            except:
                pass
            
            try:
                self.ssl_socket.close()
            except:
                pass
            
            self.connected = False
            self.session_id = None
            print("Disconnected")


# ==================== SENSOR FUNCTIONS ====================

def get_wifi_info():
    """Get WiFi connection info"""
    wlan = network.WLAN(network.STA_IF)
    if wlan.isconnected():
        return {
            "connected": True,
            "ip": wlan.ifconfig()[0],
            "signal": wlan.status("rssi")
        }
    return {"connected": False, "ip": "", "signal": 0}


def generate_sensor_data():
    """Generate simulated sensor data"""
    import random
    
    temp = 36.8 + (random.random() - 0.5) * 0.6
    humidity = 55 + (random.random() - 0.5) * 5
    
    threat = "safe"
    score = 100
    anomaly = False
    
    if temp < 36.5 or temp > 37.5:
        threat = "critical"
        score -= 30
        anomaly = True
    
    if humidity < 50 or humidity > 60:
        if threat == "safe":
            threat = "warning"
        score -= 20
        anomaly = True
    
    wifi = get_wifi_info()
    
    return {
        "device_id": DEVICE_ID,
        "temperature": round(temp, 2),
        "humidity": round(humidity, 1),
        "air_pressure": round(1013 + (random.random() - 0.5) * 5, 2),
        "oxygen_level": round(21 + random.random() * 0.5, 2),
        "motion_detected": random.random() < 0.05,
        "door_status": random.random() < 0.02,
        "vibration_level": round(random.random() * 0.3, 3),
        "power_voltage": round(12 + (random.random() - 0.5) * 0.5, 2),
        "wifi_signal_strength": wifi["signal"],
        "threat_level": threat,
        "anomaly_detected": anomaly,
        "security_score": max(0, score),
        "tls_enabled": True
    }


# ==================== MAIN LOOP ====================

def main():
    """Main firmware loop with secure TLS connection"""
    print("=" * 50)
    print("SafeEdge ESP32 Secure Firmware v2.0-TLS")
    print("Imagine Cup 2026")
    print("=" * 50)
    
    # Check WiFi
    wifi = get_wifi_info()
    if not wifi["connected"]:
        print("WiFi not connected!")
        print("Run boot.py first or check credentials")
        return
    
    print(f"WiFi Connected: {wifi['ip']}")
    print(f"Signal: {wifi['signal']} dBm")
    
    # Create secure connection
    secure_conn = SecureConnection(
        host=BACKEND_HOST,
        port=BACKEND_PORT,
        device_id=DEVICE_ID
    )
    
    # Connect with TLS
    print("\nEstablishing secure connection...")
    if not secure_conn.connect():
        print("Failed to establish secure connection")
        print("Retrying...")
        if not secure_conn.reconnect():
            print("Connection failed - check certificates and server")
            return
    
    print("\nStarting secure sensor loop...")
    print("Press Ctrl+C to stop\n")
    
    heartbeat_count = 0
    
    while True:
        try:
            # Generate and send sensor data
            data = generate_sensor_data()
            
            threat = data["threat_level"]
            score = data["security_score"]
            
            if threat == "critical":
                print(f"🔴 CRITICAL - Score: {score}")
            elif threat == "warning":
                print(f"🟡 WARNING - Score: {score}")
            else:
                print(f"🟢 SAFE - Score: {score}")
            
            # Send over secure connection
            result = secure_conn.send_sensor_data(data)
            
            if result:
                print(f"   [TLS] Data sent: Temp={data['temperature']}°C")
            else:
                print("   [TLS] Failed to send data")
            
            # Heartbeat every 30 seconds
            heartbeat_count += 1
            if heartbeat_count >= 6:
                if secure_conn.send_heartbeat():
                    print("   [TLS] Heartbeat OK")
                heartbeat_count = 0
            
            time.sleep(REPORT_INTERVAL)
            
        except KeyboardInterrupt:
            print("\nStopping...")
            secure_conn.disconnect()
            break
        except Exception as e:
            print(f"Error: {e}")
            time.sleep(5)


if __name__ == "__main__":
    main()
